### ISSUE TITLE
fix bug in an OSMNX's function (_consolidate_intersections_rebuild_graph) used in a osm_network_wrapper's function (snap_nodes_to_nodes)

### ISSUE THREAD

**Issue by sahand-asgarpour** [Deltares/ra2ce#177]
Which line: subcluster_centroid = node_points.loc[wcc].unary_union.centroid
Error: wcc should be a list instead of a set
Solution: create a wrapper of this function in osmn_network_wrapper

**Comment by LiekeMeijer** [comment]
buffered_nodes = gdf_nodes.buffer(tolerance).unary_union
C:\Users\meije_le\Anaconda3\envs\ra2ce_env_tobreak2\lib\site-packages\osmnx\simplification.py:478: UserWarning: Geometry is in a geographic CRS. Results from 'centroid' are likely incorrect. Use 'GeoSeries.to_crs()' to re-project geometries to a projected CRS before this operation.

  centroids = node_clusters.centroid
2023-09-15 11:39:27 AM - [main.py:60] - root - ERROR - Passing a set as an indexer is not supported. Use a list instead.
Traceback (most recent call last):
  File "C:\python\ra2ce\ra2ce\main.py", line 58, in <module>
    run_analysis()
  File "C:\Users\meije_le\Anaconda3\envs\ra2ce_env_tobreak2\lib\site-packages\click\core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\meije_le\Anaconda3\envs\ra2ce_env_tobreak2\lib\site-packages\click\core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "C:\Users\meije_le\Anaconda3\envs\ra2ce_env_tobreak2\lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\meije_le\Anaconda3\envs\ra2ce_env_tobreak2\lib\site-packages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "C:\python\ra2ce\ra2ce\main.py", line 52, in run_analysis
    _handler.configure()
  File "C:\python\ra2ce\ra2ce\ra2ce_handler.py", line 71, in configure
    self.input_config.configure()
  File "C:\python\ra2ce\ra2ce\configuration\config_wrapper.py", line 79, in configure
    self.network_config.configure_network()
  File "C:\python\ra2ce\ra2ce\graph\network_config_wrapper.py", line 156, in configure_network
    self.graphs = network.create()
  File "C:\python\ra2ce\ra2ce\graph\networks.py", line 219, in create
    base_graph, network_gdf = self._get_new_network_and_graph(to_save)
  File "C:\python\ra2ce\ra2ce\graph\networks.py", line 156, in _get_new_network_and_graph
    ).get_network()
  File "C:\python\ra2ce\ra2ce\graph\network_wrappers\network_wrapper_factory.py", line 62, in get_network
    return OsmNetworkWrapper(self._config_data).get_network()
  File "C:\python\ra2ce\ra2ce\graph\network_wrappers\osm_network_wrapper\osm_network_wrapper.py", line 56, in get_network
    graph_complex = self.get_clean_graph_from_osm()
  File "C:\python\ra2ce\ra2ce\graph\network_wrappers\osm_network_wrapper\osm_network_wrapper.py", line 137, in get_clean_graph_from_osm
    _complex_graph = self._download_clean_graph_from_osm(
  File "C:\python\ra2ce\ra2ce\graph\network_wrappers\osm_network_wrapper\osm_network_wrapper.py", line 182, in _download_clean_graph_from_osm
    self.get_clean_graph(_complex_graph)
  File "C:\python\ra2ce\ra2ce\graph\network_wrappers\osm_network_wrapper\osm_network_wrapper.py", line 191, in get_clean_graph
    complex_graph = OsmNetworkWrapper.snap_nodes_to_nodes(
  File "C:\python\ra2ce\ra2ce\graph\network_wrappers\osm_network_wrapper\osm_network_wrapper.py", line 303, in snap_nodes_to_nodes
    return osmnx.consolidate_intersections(
  File "C:\Users\meije_le\Anaconda3\envs\ra2ce_env_tobreak2\lib\site-packages\osmnx\simplification.py", line 406, in consolidate_intersections
    return _consolidate_intersections_rebuild_graph(
  File "C:\Users\meije_le\Anaconda3\envs\ra2ce_env_tobreak2\lib\site-packages\osmnx\simplification.py", line 501, in _consolidate_intersections_rebuild_graph
    subcluster_centroid = node_points.loc[wcc].unary_union.centroid
  File "C:\Users\meije_le\Anaconda3\envs\ra2ce_env_tobreak2\lib\site-packages\pandas\core\indexing.py", line 1091, in __getitem__
    check_dict_or_set_indexers(key)
  File "C:\Users\meije_le\Anaconda3\envs\ra2ce_env_tobreak2\lib\site-packages\pandas\core\indexing.py", line 2618, in check_dict_or_set_indexers
    raise TypeError(
TypeError: Passing a set as an indexer is not supported. Use a list instead.

**Comment by LiekeMeijer** [comment]
With the latest environment update (8/11) this issue does no longer happen anymore.
