### ISSUE TITLE
Graph cannot be reprojected if the index is not unique

### ISSUE THREAD

**Issue by keesvanginkel** [Deltares/ra2ce#83]
network_utils.py, function: reproject_graph

graph_reprojected = reproject_graph(G, in_crs, out_crs)
Traceback (most recent call last):
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2019.3.3\plugins\python-ce\helpers\pydev\_pydevd_bundle\pydevd_exec2.py", line 3, in Exec
    exec(exp, global_vars, local_vars)
  File "<input>", line 1, in <module>
  File "D:\Python\ra2ce\ra2ce\graph\networks_utils.py", line 1729, in reproject_graph
    set_values = gdf_out.to_dict(orient="index")
  File "C:\Users\Ginkel\AppData\Local\Continuum\anaconda3\envs\ra2ce_env\lib\site-packages\pandas\core\frame.py", line 1953, in to_dict
    raise ValueError("DataFrame index must be unique for orient='index'.")
ValueError: DataFrame index must be unique for orient='index'.

**Comment by MatthiasHauthDeltares** [comment]
to be investigated if it is still relevant. I think RA2CE creates a rfc_id when the id is not unique.
Anyway, the documentation should explain the id **_### clearly._**
